import { buildAccountingSummaries } from "@/lib/accounting";
import { withFundraisingSummaries } from "@/lib/fundraising";
import { buildRetainerPeriodsFromAccountingDocuments } from "@/lib/retainer-forecast";
import type { AccountingDocument, AccountingLedgerEntry, Company, DashboardData, FundraisingClient, FundraisingClientTarget, InvestmentRelationship, Tag, Task } from "@/lib/types";

const tags: Tag[] = [
  { id: "tag-financial-services", name: "Financial Services", color: "#2563eb" },
  { id: "tag-family-office", name: "Family Office", color: "#7c3aed" },
  { id: "tag-priority", name: "Priority", color: "#dc2626" },
  { id: "tag-europe", name: "Europe", color: "#059669" },
  { id: "tag-review", name: "Needs Review", color: "#d97706" },
];

const morganStanleyInvestment: InvestmentRelationship = {
  id: "investment-ms-company",
  companyId: "company-morgan-stanley",
  personId: null,
  investmentStatus: "past_investor",
  capacityStatus: "fully_allocated",
  notes: "Demo relationship showing a past investor that is currently fully allocated.",
  lastInvestedDate: "2025-11-18",
  deals: [
    {
      id: "deal-ms-2025",
      name: "2025 Co-investment",
      status: "closed",
      investedAt: "2025-11-18",
      notes: "Demo historical deal.",
      role: "Investor",
    },
  ],
};

const goldmanInvestment: InvestmentRelationship = {
  id: "investment-gs-company",
  companyId: "company-goldman",
  personId: null,
  investmentStatus: "current_investor",
  capacityStatus: "available",
  notes: "Demo current investor relationship.",
  lastInvestedDate: "2026-02-10",
  deals: [
    {
      id: "deal-gs-active",
      name: "Active Growth Deal",
      status: "active",
      investedAt: "2026-02-10",
      notes: null,
      role: "Investor",
    },
  ],
};

const companies: Company[] = [
  {
    id: "company-morgan-stanley",
    name: "Morgan Stanley",
    normalizedName: "morgan stanley",
    websiteDomain: "morganstanley.com",
    websiteDomains: ["morganstanley.com"],
    description: "Imported company profile merged from workbook contacts and corporate email domains.",
    country: "United States of America",
    categories: ["Financial Services", "Investment Banking"],
    status: "active",
    ownerName: "Mohammed",
    sourceQuality: "high",
    outreachStage: "Selected",
    tags: [tags[0], tags[2]],
    people: [
      {
        id: "person-ms-1",
        sourcePersonIds: ["person-ms-1"],
        displayName: "Senior Banking Contact",
        firstName: null,
        lastName: null,
        email: "contact@morganstanley.com",
        emails: ["contact@morganstanley.com", "senior.banker@morganstanley.com"],
        phone: null,
        linkedinUrl: "https://www.linkedin.com/",
        jobTitle: "Executive Director",
        country: "United States of America",
        categories: ["Financial Services"],
        connectionStrength: "Very weak",
        highlighted: true,
        investmentRelationships: [],
      },
      {
        id: "person-ms-2",
        sourcePersonIds: ["person-ms-2"],
        displayName: "Lender Finance Contact",
        firstName: null,
        lastName: null,
        email: "lender@morganstanley.com",
        emails: ["lender@morganstanley.com"],
        phone: null,
        linkedinUrl: null,
        jobTitle: "Head of Lender Finance Collateral Underwriting",
        country: "United States of America",
        categories: ["Financial Services"],
        connectionStrength: "Weak",
        highlighted: false,
        investmentRelationships: [],
      },
    ],
    activities: [
      { id: "activity-ms-1", type: "note", summary: "Imported as high-confidence company/domain match.", occurredAt: "2026-04-23T09:30:00Z" },
    ],
    nextTask: { id: "task-ms-1", title: "Review highlighted contact before outreach", dueDate: "2026-04-29", status: "open", companyId: "company-morgan-stanley" },
    lastActivityAt: "2026-04-23T09:30:00Z",
    mergeConfidence: 0.96,
    enrichment: null,
    investmentRelationships: [morganStanleyInvestment],
  },
  {
    id: "company-alphasights",
    name: "AlphaSights",
    normalizedName: "alphasights",
    websiteDomain: "alphasights.com",
    websiteDomains: ["alphasights.com"],
    description: "Repeated workbook company with many matching email-domain contacts.",
    country: "United Kingdom",
    categories: ["Research", "Information Services"],
    status: "active",
    ownerName: "Team",
    sourceQuality: "high",
    outreachStage: "Ready to Contact",
    tags: [tags[2], tags[3]],
    people: [
      {
        id: "person-alpha-1",
        sourcePersonIds: ["person-alpha-1"],
        displayName: "Business Development Executive",
        firstName: null,
        lastName: null,
        email: "bd@alphasights.com",
        emails: ["bd@alphasights.com", "business.dev@alphasights.com"],
        phone: null,
        linkedinUrl: "https://www.linkedin.com/",
        jobTitle: "Business Development Executive",
        country: "United Kingdom",
        categories: ["Research"],
        connectionStrength: "Very weak",
        highlighted: true,
        investmentRelationships: [],
      },
    ],
    activities: [
      { id: "activity-alpha-1", type: "status_change", summary: "Moved to Ready to Contact.", occurredAt: "2026-04-22T14:15:00Z" },
    ],
    nextTask: { id: "task-alpha-1", title: "Draft first-touch note", dueDate: "2026-04-26", status: "open", companyId: "company-alphasights" },
    lastActivityAt: "2026-04-22T14:15:00Z",
    mergeConfidence: 0.94,
    enrichment: {
      companyId: "company-alphasights",
      status: "completed",
      summary: "Knowledge services business used as demo enrichment data.",
      industry: "Information Services",
      subsector: "Expert networks",
      companyType: "Services",
      location: "United Kingdom",
      keywords: ["research", "expert network", "information services"],
      sourceUrl: "https://alphasights.com",
      model: "demo",
      confidence: 0.78,
      errorMessage: null,
      generatedAt: "2026-04-22T14:15:00Z",
      reviewedAt: null,
      updatedAt: "2026-04-22T14:15:00Z",
    },
    investmentRelationships: [],
  },
  {
    id: "company-unnamed",
    name: "Unnamed company",
    normalizedName: "unnamed company",
    websiteDomain: null,
    websiteDomains: [],
    description: "Low-confidence imported records that need cleanup before use.",
    country: null,
    categories: ["Unknown"],
    status: "review",
    ownerName: null,
    sourceQuality: "review",
    outreachStage: "Research",
    tags: [tags[4]],
    people: [
      {
        id: "person-unnamed-1",
        sourcePersonIds: ["person-unnamed-1"],
        displayName: "Imported email-only contact",
        firstName: null,
        lastName: null,
        email: "contact@gmail.com",
        emails: ["contact@gmail.com"],
        phone: null,
        linkedinUrl: null,
        jobTitle: null,
        country: null,
        categories: [],
        connectionStrength: "Very weak",
        highlighted: false,
        investmentRelationships: [],
      },
    ],
    activities: [
      { id: "activity-unnamed-1", type: "note", summary: "Personal email domain prevented automatic company-domain merge.", occurredAt: "2026-04-21T11:00:00Z" },
    ],
    nextTask: null,
    lastActivityAt: "2026-04-21T11:00:00Z",
    mergeConfidence: 0.41,
    enrichment: null,
    investmentRelationships: [],
  },
  {
    id: "company-goldman",
    name: "Goldman Sachs",
    normalizedName: "goldman sachs",
    websiteDomain: "goldmansachs.com",
    websiteDomains: ["goldmansachs.com"],
    description: "Corporate-domain contacts merged into one company profile.",
    country: "United States of America",
    categories: ["Financial Services", "Investment Banking"],
    status: "active",
    ownerName: "Mohammed",
    sourceQuality: "high",
    outreachStage: "Contacted",
    tags: [tags[0]],
    people: [
      {
        id: "person-gs-1",
        sourcePersonIds: ["person-gs-1"],
        displayName: "Capital Markets Contact",
        firstName: null,
        lastName: null,
        email: "markets@goldmansachs.com",
        emails: ["markets@goldmansachs.com"],
        phone: null,
        linkedinUrl: "https://www.linkedin.com/",
        jobTitle: "Vice President",
        country: "United States of America",
        categories: ["Financial Services"],
        connectionStrength: "Weak",
        highlighted: true,
        investmentRelationships: [],
      },
    ],
    activities: [
      { id: "activity-gs-1", type: "email", summary: "Manual outreach logged.", occurredAt: "2026-04-20T16:45:00Z" },
    ],
    nextTask: { id: "task-gs-1", title: "Follow up on initial note", dueDate: "2026-04-30", status: "open", companyId: "company-goldman" },
    lastActivityAt: "2026-04-20T16:45:00Z",
    mergeConfidence: 0.95,
    enrichment: null,
    investmentRelationships: [goldmanInvestment],
  },
];

const tasks: Task[] = companies.flatMap((company) => (company.nextTask ? [company.nextTask] : []));
const accountingDocuments: AccountingDocument[] = [
  {
    id: "accounting-doc-retainer-ms",
    companyId: "company-morgan-stanley",
    fundraisingClientId: "client-ms-raise",
    retainerPeriodDate: "2026-04-15",
    documentType: "retainer",
    status: "partially_paid",
    title: "Monthly fundraising retainer",
    amountMinor: 2500000,
    currency: "GBP",
    issuedOn: "2026-04-01",
    dueOn: "2026-04-15",
    externalReference: "RET-MS-2026-04",
    documentUrl: null,
    notes: "Demo retainer for a signed fundraising mandate.",
    createdBy: null,
    updatedBy: null,
    voidedAt: null,
    voidedBy: null,
    voidReason: null,
    createdAt: "2026-04-01T09:00:00Z",
    updatedAt: "2026-04-20T09:00:00Z",
  },
  {
    id: "accounting-doc-commission-gs",
    companyId: "company-goldman",
    fundraisingClientId: null,
    retainerPeriodDate: null,
    documentType: "commission",
    status: "open",
    title: "Success commission",
    amountMinor: 4250000,
    currency: "USD",
    issuedOn: "2026-04-10",
    dueOn: "2026-05-10",
    externalReference: "COMM-GS-01",
    documentUrl: null,
    notes: "Demo cash commission receivable.",
    createdBy: null,
    updatedBy: null,
    voidedAt: null,
    voidedBy: null,
    voidReason: null,
    createdAt: "2026-04-10T09:00:00Z",
    updatedAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "accounting-doc-expense-travel",
    companyId: "company-alphasights",
    fundraisingClientId: null,
    retainerPeriodDate: null,
    documentType: "expense",
    status: "paid",
    title: "Client meeting travel",
    amountMinor: 48000,
    currency: "GBP",
    issuedOn: "2026-04-18",
    dueOn: null,
    externalReference: "EXP-TRAVEL-01",
    documentUrl: null,
    notes: "Demo reimbursable expense.",
    createdBy: null,
    updatedBy: null,
    voidedAt: null,
    voidedBy: null,
    voidReason: null,
    createdAt: "2026-04-18T09:00:00Z",
    updatedAt: "2026-04-18T09:00:00Z",
  },
];
const accountingLedgerEntries: AccountingLedgerEntry[] = [
  {
    id: "accounting-entry-retainer-ms",
    documentId: "accounting-doc-retainer-ms",
    companyId: "company-morgan-stanley",
    entryType: "retainer_payment",
    direction: "incoming",
    amountMinor: 1500000,
    currency: "GBP",
    occurredOn: "2026-04-16",
    externalReference: "BANK-RET-MS",
    documentUrl: null,
    notes: "Demo partial retainer payment.",
    createdBy: null,
    updatedBy: null,
    voidedAt: null,
    voidedBy: null,
    voidReason: null,
    createdAt: "2026-04-16T09:00:00Z",
    updatedAt: "2026-04-16T09:00:00Z",
  },
  {
    id: "accounting-entry-expense-travel",
    documentId: "accounting-doc-expense-travel",
    companyId: "company-alphasights",
    entryType: "expense_payment",
    direction: "outgoing",
    amountMinor: 48000,
    currency: "GBP",
    occurredOn: "2026-04-18",
    externalReference: "CARD-TRAVEL",
    documentUrl: null,
    notes: "Demo card expense.",
    createdBy: null,
    updatedBy: null,
    voidedAt: null,
    voidedBy: null,
    voidReason: null,
    createdAt: "2026-04-18T09:00:00Z",
    updatedAt: "2026-04-18T09:00:00Z",
  },
];
const fundraisingClients: FundraisingClient[] = [
  {
    id: "client-ms-raise",
    companyId: "company-morgan-stanley",
    mandateName: "Morgan Stanley strategic raise",
    stage: "investor_outreach",
    ownerId: null,
    primaryContactPersonId: "person-ms-1",
    signedOn: "2026-03-20",
    targetRaiseAmountMinor: 2000000000,
    targetRaiseCurrency: "GBP",
    retainerAmountMinor: 50000000,
    retainerCurrency: "GBP",
    retainerCadence: "monthly",
    retainerSchedule: "Monthly on 15th",
    retainerNextBillingDate: "2026-05-15",
    materialsUrl: null,
    dataRoomUrl: null,
    notes: "Demo signed client mandate with active investor outreach.",
    createdBy: null,
    updatedBy: null,
    createdAt: "2026-03-20T09:00:00Z",
    updatedAt: "2026-04-22T09:00:00Z",
  },
  {
    id: "client-gs-raise",
    companyId: "company-goldman",
    mandateName: "Goldman growth capital mandate",
    stage: "meetings",
    ownerId: null,
    primaryContactPersonId: "person-gs-1",
    signedOn: "2026-04-02",
    targetRaiseAmountMinor: 1500000000,
    targetRaiseCurrency: "USD",
    retainerAmountMinor: null,
    retainerCurrency: null,
    retainerCadence: null,
    retainerSchedule: null,
    retainerNextBillingDate: null,
    materialsUrl: null,
    dataRoomUrl: null,
    notes: "Demo client with investor meetings underway.",
    createdBy: null,
    updatedBy: null,
    createdAt: "2026-04-02T09:00:00Z",
    updatedAt: "2026-04-21T09:00:00Z",
  },
];
const fundraisingTargets: FundraisingClientTarget[] = [
  {
    id: "target-ms-alpha",
    clientId: "client-ms-raise",
    investorCompanyId: "company-alphasights",
    investorPersonId: "person-alpha-1",
    investorName: "AlphaSights",
    investorEmail: "bd@alphasights.com",
    investorType: "Family Office",
    ticketSizeMinMinor: 25000000,
    ticketSizeMaxMinor: 75000000,
    ticketSizeCurrency: "GBP",
    stage: "contacted",
    ownerId: null,
    lastContactedAt: "2026-04-20T10:00:00Z",
    nextStep: "Send refreshed deck",
    notes: "Interested in services-led growth exposure.",
    createdBy: null,
    updatedBy: null,
    createdAt: "2026-04-10T09:00:00Z",
    updatedAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "target-ms-goldman",
    clientId: "client-ms-raise",
    investorCompanyId: "company-goldman",
    investorPersonId: "person-gs-1",
    investorName: "Goldman Sachs",
    investorEmail: "markets@goldmansachs.com",
    investorType: "Institutional Investor",
    ticketSizeMinMinor: 100000000,
    ticketSizeMaxMinor: 200000000,
    ticketSizeCurrency: "GBP",
    stage: "meeting",
    ownerId: null,
    lastContactedAt: "2026-04-22T14:00:00Z",
    nextStep: "Follow up after partner call",
    notes: null,
    createdBy: null,
    updatedBy: null,
    createdAt: "2026-04-11T09:00:00Z",
    updatedAt: "2026-04-22T14:00:00Z",
  },
  {
    id: "target-gs-ms",
    clientId: "client-gs-raise",
    investorCompanyId: "company-morgan-stanley",
    investorPersonId: "person-ms-1",
    investorName: "Morgan Stanley",
    investorEmail: "contact@morganstanley.com",
    investorType: "Private Equity",
    ticketSizeMinMinor: 50000000,
    ticketSizeMaxMinor: 150000000,
    ticketSizeCurrency: "USD",
    stage: "replied",
    ownerId: null,
    lastContactedAt: "2026-04-19T15:30:00Z",
    nextStep: "Share data room access",
    notes: "Asked for additional market sizing.",
    createdBy: null,
    updatedBy: null,
    createdAt: "2026-04-09T09:00:00Z",
    updatedAt: "2026-04-19T15:30:00Z",
  },
];
const accountingData = {
  documents: accountingDocuments,
  ledgerEntries: accountingLedgerEntries,
  summaries: buildAccountingSummaries(accountingDocuments, accountingLedgerEntries),
};

export const mockDashboardData: DashboardData = {
  currentUserName: "Demo user",
  companies,
  tags,
  tasks,
  importSummary: {
    totalRows: 18623,
    rawRows: 18623,
    normalizedCompanies: 11408,
    normalizedPeople: 18623,
    suspiciousMerges: 80,
    unmatchedRows: 1198,
    lastImportedAt: null,
  },
  accountingAccess: {
    canView: true,
    canEdit: true,
    canAdmin: true,
    role: "admin",
  },
  accounting: accountingData,
  clientDashboard: withFundraisingSummaries({
    clients: fundraisingClients,
    targets: fundraisingTargets,
    retainerPeriods: buildRetainerPeriodsFromAccountingDocuments(accountingDocuments, "2026-04-20"),
  }, accountingData),
  authMode: "demo",
  dataMode: "demo",
  localEnrichmentEnabled: false,
  dataWarning: "Demo contacts are loaded.",
};
